### ISSUE TITLE
what is licence of this codes?

### ISSUE THREAD

**Issue by ryogrid** [pzhzqt/goostub#1]
@pzhzqt 
hi. pzhzqt.
Codes of this repo are great and I want to praise your work.

Then, I want to know licence of codes on this repo.
Because, I plan writing RDB in Golang like you and I want use your codes.

I think you can apply any licence you want because this repo does not include codes of BusTub which is wrote in cpp.

regards,
ryo_grid

**Comment by pzhzqt** [comment]
Hi Ryo,

I just added license to this repo.

As I got busier and later my interest in Go waned, this was left halfway undone. I believe even the existing files aren't fully finished.

Nevertheless, feel free to use any of my code. I might someday pick this up myself haha.

**Comment by ryogrid** [comment]
@pzhzqt 
Thank you for your fast response for my question!

Regards,
ryo_grid
